[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

#contracts = 'contracts'  # The source directory
#libs = ['modules']       # A list of library directories
solc_version = '0.8.17'   # Override for the solc version (setting this ignores `auto_detect_solc`)
optimizer = true         # Enable or disable the solc optimizer
optimizer_runs = 200     # The number of optimizer runs
verbosity = 2            # The verbosity of tests

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.local]
fuzz_runs = 100

[profile.deep]
fuzz_runs = 50000

[profile.super_deep]
fuzz_runs = 500000
